meta_product_name: "Dissensium"
meta_title: "Dissensium - Obtenez des décisions plus créatives"
meta_description: "Organisez facilement des réunions et générer plus d'idées"
meta_image: "logo-dissensium-bleu.png"                       # should exist in `app/assets/images/`
